services:
  grafana:
    image: grafana/grafana:9.5.2

    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_DISABLE_SIGNOUT_MENU=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/dashboards/home.json
      - GF_SERVER_ROOT_URL=http://localhost:8080/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - INTERNETNL_DOMAINNAME

    volumes:
      - ./monitoring/grafana/dashboards/:/etc/dashboards
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-data:/var/lib/grafana

    restart: on-failure
    networks:
      - internal

  prometheus:
    image: prom/prometheus:v2.44.0

    command:
      - --config.file=/prometheus.yaml
      - --web.external-url=/prometheus/
      - --storage.tsdb.retention=5y
      - --web.enable-admin-api

    restart: on-failure
    networks:
      - internal

    volumes:
      - ./monitoring/prometheus/prometheus.yaml:/prometheus.yaml
      - prometheus-data:/prometheus

  postgresql-exporter:
    image: prometheuscommunity/postgres-exporter:v0.12.0

    environment:
      - DATA_SOURCE_NAME=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable

    restart: on-failure
    networks:
      - internal

  redis-exporter:
    image: oliver006/redis_exporter:v1.50.0

    environment:
      - REDIS_ADDR=redis://redis:6379

    restart: on-failure
    networks:
      - internal

  statsd-exporter:
    image: prom/statsd-exporter:v0.23.1

    command:
      - --statsd.listen-udp=:8125
      - --statsd.listen-tcp=:8125

    restart: on-failure
    networks:
      internal:
        ipv4_address: $IPV4_IP_STATSD_INTERNAL
        aliases:
          - statsd

volumes:
  # permanent storage for Prometheus metrics
  prometheus-data: {}
  # permanent storage for Grafana custom dashboards
  grafana-data: {}
