services:
  # networks during tests are cut off from the outside to provide isolated test results
  # to provide some debugging possibilities this container is used to expose some ports
  # from the internal network to the outside
  port-expose:
    image: alpine/socat
    entrypoint: /bin/sh
    command: -c "socat TCP-LISTEN:8081,reuseaddr,fork TCP:webserver:80|socat TCP-LISTEN:15672,reuseaddr,fork TCP:rabbitmq:15672"
    networks:
      - public-internet
      - port-expose
    ports:
      - 8081:8081
      - 15672:15672

  app:
    dns: $IPV4_IP_RESOLVER_INTERNAL
    # TODO: does this solve issues with slow tests on Github Actions?
    dns_search: []
    dns_opt: ["ndots:0", "timeout:1", "attempts:1"]
  worker:
    dns: $IPV4_IP_RESOLVER_INTERNAL
    # TODO: does this solve issues with slow tests on Github Actions?
    dns_search: []
    dns_opt: ["ndots:0", "timeout:1", "attempts:1"]

  rabbitmq:
    networks:
      - internal
      - public-internet
    ports:
      # expose admin GUI to localhost
      - $RABBITMQ_GUI

  test-target:
    image: nginx

    networks:
      public-internet:
        ipv4_address: $IPV4_IP_TEST_TARGET_PUBLIC
        ipv6_address: $IPV6_IP_TEST_TARGET_PUBLIC

    ports:
      - 80
      - 443

    volumes:
      - ./integration-tests/nginx_templates/:/etc/nginx/templates/
      - ./integration-tests/pki:/etc/pki/
      - ./integration-tests/www:/var/www/

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: $HEALTHCHECK_INTERVAL
      retries: 30

  mail-test-target:
    image: mailhog/mailhog

    networks:
      public-internet:
        ipv4_address: $IPV4_IP_TEST_TARGET_MAIL_PUBLIC
        ipv6_address: $IPV6_IP_TEST_TARGET_MAIL_PUBLIC

    ports:
      - 25

    environment:
      MH_SMTP_BIND_ADDR: 0.0.0.0:25

    # healthcheck:
    #   test: ["CMD", "nc", "localhost", "25"]
    #   interval: $HEALTHCHECK_INTERVAL
    #   retries: 30

  resolver:
    image: strm/dnsmasq

    entrypoint: /entrypoint.sh

    networks:
      internal:
        ipv4_address: $IPV4_IP_RESOLVER_INTERNAL

    # null route external DNS queries to isolate tests
    dns: 192.0.2.1

    ports:
      - "53/udp"

    environment:
      - IPV4_IP_UNBOUND_INTERNAL

    volumes:
      - ./integration-tests/dnsmasq/entrypoint.sh:/entrypoint.sh

    cap_add:
      - NET_ADMIN

  webserver:
    networks:
      public-internet:
        ipv6_address: $IPV6_IP_PUBLIC
        ipv4_address: $IPV4_WEBSERVER_IP_PUBLIC

  unbound:
    networks:
      public-internet:
        ipv4_address: $IPV4_UNBOUND_IP_PUBLIC

networks:
  # network that is not internet to expose internal ports for debugging purposes
  port-expose:
    internal: false
    driver: bridge

  public-internet:
    # make public network internal as well to run tests isolated from the internet
    internal: true
    # required to enable IPv6 on Docker Desktop runtime
    enable_ipv6: true
    driver: bridge
    driver_opts:
      # required to enable IPv6 on Colima Docker runtime
      com.docker.network.enable_ipv6: "true"
      # network for internal communication between services
      com.docker.network.bridge.enable_icc: "true"
    ipam:
      driver: default
      config:
      - subnet: $IPV6_SUBNET_PUBLIC
        gateway: $IPV6_GATEWAY_PUBLIC
      - subnet: $IPV4_SUBNET_PUBLIC
